
// Muestra todos las películas de la base de datos
GET http://localhost:3000/movies
Content-Type: application/json
###

// Muestra una película según su _id
GET http://localhost:3000/movies/id/6455971c8cfbabd997af3be7
Content-Type: application/json
###

// Muestrael director de una peli según su título
GET http://localhost:3000/movies/title/Os Bingueiros
Content-Type: application/json
###

// Muestra una película según su género
GET http://localhost:3000/movies/genre/Animación
Content-Type: application/json
###

// Muestra una película estrenadas a partir de 2010
GET http://localhost:3000/movies/year2010
Content-Type: application/json
###

// Añade una nueva película la base de datos
POST http://localhost:3000/movies
Content-Type: application/json

{
        "title": "Los bingueros",
        "director": "Andrés Pajares",
        "year": 1979,
        "genre": "Drama"
}
###
// Modifica película enviando su _id por la url
PUT http://localhost:3000/movies/6455abc9ba9bf2adf191e916
Content-Type: application/json

{
        "title": "Os Bingueiros",
        "director": "Andrés Paixares",
        "year": 1979,
        "genre": "Drama"
}
###
//Elimina películas mandando su _id
DELETE http://localhost:3000/movies/64559a48fe12ff60b4e50d1c
Content-Type: application/json

###